apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-legacy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: stwomack/node-app-legacy:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: db-secret
          imagePullPolicy: Always
