apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kpack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-kpack
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-kpack
    spec:
      containers:
        - name: node-kpack
          image: stwomack/node-kpack:latest
          ports:
            - containerPort: 3000