apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: node-kpack-image
  namespace: default
spec:
  tag: stwomack/node-kpack
  serviceAccountName: main-builder-service-account
  builder:
    name: main-builder
    kind: Builder
  source:
    git:
      url: https://github.com/stwomack/node-kpack
      revision: main
