apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: node-app-image
  namespace: default
spec:
  tag: stwomack/node-app
  serviceAccountName: main-builder-service-account
  builder:
    name: main-builder
    kind: Builder
  source:
    git:
      url: https://github.com/stwomack/node-app
      revision: main